---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-arc-pat
  namespace: arc-runners
spec:
  encryptedData:
    github_token: AgAaXdQTavvxE1YOJnCtYkoG86qBE87FVEkAYyOUztLR8B3vRxu9cd/+NBXjrsEckf/nZ+awA9I+tXleTflLJVWn/e2fajSvjLPq+2eG8Kei5W2dHrwRPlldLwbKHsnJscxySHVrkBVDlCasWA+CZBPZen7X+aE771RY2clvJEAEAWdnMH9HGRAYIX6N65gpomkVikTDNB2GbuTqjsqpFaJrlShUr6YKvRMPrJCFZK1azo5Fw1FTk5CLAl+yeKwMd5yBiVPvwH2yFHFYmj/oYS/sqLDja6s5dZnAh3AvW84YR6bsCrHKlZLXCyLrw+D2T2/TmFdO2cpglXJ5Fppen80fYnknOkLJ0cEcjLROT1v51C70BdvHQvVuYO+T7TGC4LK5z4qaFj6ZmgyxW6c8wDasgTCWlkLncz1eyTdg5NQ7AwJygsovkxDCqWqZJIU1HYaG9HrkdarK1AzEWBexKUmTfdSJisuu898Cwj24a+IsODY6bI3VG0ThQC9wlObF16At7VNkFEEEFHNnV5X+gj1cTdCyy49NfmrEa/p+KMgO2BlOls4AgQvABxPpAXT2FevunBEUvAZGvE7+eKoHi+EdWM4liWZ7ILEXX9Iay3uamKOXGvssaBPdgmRTL9tzr7hrh3oaWXUklKPua4O/jbxKf8AQZgH0AJG/5ITYYNjY7RrVGSZhvoA4KWPBv2Jss3NJbLdBtY5bCt6W9D+rMw+Q0lI6lkzoBg4pOLZEhfDDNN4cj6P/Y9wPApDNujWL0sQlkmhPeT1QnoI5YobZLU7EnUgK/xWP0+1yoQ9DdPqtr9N6EkuugBRXtGDsCM8=
  template:
    metadata:
      name: github-arc-pat
      namespace: arc-runners
